In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import nltk
# # nltk.download('wordnet')

from ast import literal_eval

In [26]:
emo=pd.read_csv('spotify_emo.csv')

In [27]:
emo.drop(['artist', 'lem','cleaned_lyrics', 'emotion'], axis=1, inplace=True)

In [28]:
emo['lyrics_emo'] = emo['lyrics_emo'].apply(literal_eval) #문자열 표현식으로 인식 변환

In [29]:
emo

                      song                                         lyrics_emo
0                 Everyday  {'disgust': 6, 'negative': 11, 'positive': 11,...
1         Live Till We Die  {'anger': 1, 'disgust': 1, 'fear': 27, 'negati...
2            The Otherside  {'positive': 5, 'trust': 3, 'joy': 1, 'anticip...
3                    Pinot  {'joy': 16, 'positive': 23, 'fear': 6, 'surpri...
4       Shadows & Diamonds  {'positive': 14, 'joy': 12, 'trust': 11, 'nega...
...                    ...                                                ...
158348     Friends of Mine  {'anticipation': 7, 'joy': 11, 'positive': 11,...
158349      Frozen in Time  {'anticipation': 12, 'fear': 2, 'trust': 6, 'j...
158350   Hard to Be a Girl  {'disgust': 5, 'negative': 5, 'anticipation': ...
158351         I Wanna Die  {'fear': 5, 'negative': 8, 'sadness': 7, 'trus...
158352     Musical Ladders  {'anger': 1, 'anticipation': 8, 'joy': 12, 'po...

[158353 rows x 2 columns]

In [35]:
emo['lyrics_emo'][4]

{'positive': 14,
 'joy': 12,
 'trust': 11,
 'negative': 6,
 'sadness': 3,
 'surprise': 2,
 'disgust': 4,
 'anger': 1,
 'fear': 1,
 'song': 'Shadows & Diamonds'}

In [ ]:
# 참고 주소 딕셔너리의 키를 어떻게 열로? 
# How to Add Dictionary Keys and Values as Pandas Columns?
# https://www.datasciencelearner.com/how-to-add-dictionary-keys-and-values-as-pandas-columns/

In [31]:
rows=[]
df = emo['lyrics_emo']
for song, row in zip(emo['song'], df):
    row['song'] = song
    rows.append(row)
    
data = pd.DataFrame(rows)
data

,disgust,negative,positive,trust,anticipation,fear,anger,joy,surprise,sadness,song
0,6.0,11.0,11.0,9.0,8.0,8.0,9.0,3.0,8.0,6.0,Everyday
1,1.0,30.0,8.0,9.0,3.0,27.0,1.0,5.0,2.0,27.0,Live Till We Die
2,6.0,10.0,5.0,3.0,3.0,2.0,6.0,1.0,8.0,6.0,The Otherside
3,5.0,11.0,23.0,9.0,6.0,6.0,6.0,16.0,2.0,5.0,Pinot
4,4.0,6.0,14.0,11.0,NaN,1.0,1.0,12.0,2.0,3.0,Shadows & Diamonds
...,...,...,...,...,...,...,...,...,...,...,...
158348,2.0,12.0,11.0,8.0,7.0,4.0,1.0,11.0,9.0,8.0,Friends of Mine
158349,1.0,2.0,8.0,6.0,12.0,2.0,1.0,4.0,3.0,1.0,Frozen in Time
158350,5.0,5.0,10.0,6.0,6.0,2.0,3.0,4.0,2.0,2.0,Hard to Be a Girl
158351,5.0,8.0,8.0,3.0,2.0,5.0,2.0,3.0,3.0,7.0,I Wanna Die
158352,1.0,5.0,14.0,9.0,8.0,1.0,1.0,12.0,9.0,2.0,Musical Ladders

In [32]:
data.columns

Index(['disgust', 'negative', 'positive', 'trust', 'anticipation', 'fear',
       'anger', 'joy', 'surprise', 'sadness', 'song'],
      dtype='object')

In [38]:
# 데이터프레임 컬럼 순서 변경 - 'song'열이 맨 앞으로 오게 했습니다-
data=data[['song','disgust', 'negative', 'positive', 'trust', 'anticipation', 'fear',
       'anger', 'joy', 'surprise', 'sadness']]

In [39]:
data

,song,disgust,negative,positive,trust,anticipation,fear,anger,joy,surprise,sadness
0,Everyday,6.0,11.0,11.0,9.0,8.0,8.0,9.0,3.0,8.0,6.0
1,Live Till We Die,1.0,30.0,8.0,9.0,3.0,27.0,1.0,5.0,2.0,27.0
2,The Otherside,6.0,10.0,5.0,3.0,3.0,2.0,6.0,1.0,8.0,6.0
3,Pinot,5.0,11.0,23.0,9.0,6.0,6.0,6.0,16.0,2.0,5.0
4,Shadows & Diamonds,4.0,6.0,14.0,11.0,NaN,1.0,1.0,12.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
158348,Friends of Mine,2.0,12.0,11.0,8.0,7.0,4.0,1.0,11.0,9.0,8.0
158349,Frozen in Time,1.0,2.0,8.0,6.0,12.0,2.0,1.0,4.0,3.0,1.0
158350,Hard to Be a Girl,5.0,5.0,10.0,6.0,6.0,2.0,3.0,4.0,2.0,2.0
158351,I Wanna Die,5.0,8.0,8.0,3.0,2.0,5.0,2.0,3.0,3.0,7.0
158352,Musical Ladders,1.0,5.0,14.0,9.0,8.0,1.0,1.0,12.0,9.0,2.0

In [41]:
# 인덱스 4인 열을 보면 4.0	6.0	14.0	11.0	NaN	1.0	1.0	12.0	2.0	3.0 이 있는데 
# emo['lyrics_emo'][4]를 확인해보면 anticipation이 빠진 {'positive': 14, 'joy': 12,'trust': 11,'negative': 6,
#                                               'sadness': 3,'surprise': 2,'disgust': 4,
#                                               'anger': 1,'fear': 1,'song': 'Shadows & Diamonds'}로 되어있습니다.

In [42]:
emo['lyrics_emo'][4]

{'positive': 14,
 'joy': 12,
 'trust': 11,
 'negative': 6,
 'sadness': 3,
 'surprise': 2,
 'disgust': 4,
 'anger': 1,
 'fear': 1,
 'song': 'Shadows & Diamonds'}

In [43]:
# 수치가 0인 감정선은 Nan으로 나타나 이를 0으로 변경해줍니다.
data.fillna(0, inplace=True)

In [44]:
data

,song,disgust,negative,positive,trust,anticipation,fear,anger,joy,surprise,sadness
0,Everyday,6.0,11.0,11.0,9.0,8.0,8.0,9.0,3.0,8.0,6.0
1,Live Till We Die,1.0,30.0,8.0,9.0,3.0,27.0,1.0,5.0,2.0,27.0
2,The Otherside,6.0,10.0,5.0,3.0,3.0,2.0,6.0,1.0,8.0,6.0
3,Pinot,5.0,11.0,23.0,9.0,6.0,6.0,6.0,16.0,2.0,5.0
4,Shadows & Diamonds,4.0,6.0,14.0,11.0,0.0,1.0,1.0,12.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
158348,Friends of Mine,2.0,12.0,11.0,8.0,7.0,4.0,1.0,11.0,9.0,8.0
158349,Frozen in Time,1.0,2.0,8.0,6.0,12.0,2.0,1.0,4.0,3.0,1.0
158350,Hard to Be a Girl,5.0,5.0,10.0,6.0,6.0,2.0,3.0,4.0,2.0,2.0
158351,I Wanna Die,5.0,8.0,8.0,3.0,2.0,5.0,2.0,3.0,3.0,7.0
158352,Musical Ladders,1.0,5.0,14.0,9.0,8.0,1.0,1.0,12.0,9.0,2.0